// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineReasoningContentComponent } from '@tylertech/forge-extended';

import { ReasoningContentComponent } from './reasoning-content.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ReasoningContentComponent],
  exports: [ReasoningContentComponent]
})
export class ForgeExtendedReasoningContentModule {
  constructor() {
    defineReasoningContentComponent();
  }
}
