// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ReasoningContentComponent as ReasoningContentComponentCustomElement,
  defineReasoningContentComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-reasoning-content',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ReasoningContentComponent {
  protected elementRef = inject<ElementRef<ReasoningContentComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-reasoning-content element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineReasoningContentComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
