// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiTooltipComponent } from '@tylertech/forge-extended';

import { ForgeAiTooltipComponent } from './forge-ai-tooltip.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiTooltipComponent],
  exports: [ForgeAiTooltipComponent]
})
export class ForgeExtendedForgeAiTooltipModule {
  constructor() {
    defineForgeAiTooltipComponent();
  }
}
