// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextEditorComponent } from '@tylertech/forge-extended';

import { RichTextEditorComponent } from './rich-text-editor.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextEditorComponent],
  exports: [RichTextEditorComponent]
})
export class ForgeExtendedRichTextEditorModule {
  constructor() {
    defineRichTextEditorComponent();
  }
}
