// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  LandingPageLayoutComponent as LandingPageLayoutComponentCustomElement,
  defineLandingPageLayoutComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-landing-page-layout',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class LandingPageLayoutComponent {
  protected elementRef = inject<ElementRef<LandingPageLayoutComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-landing-page-layout element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls the body column layout: `two-third` (default), `equal`, `three`, or `single`. */
  @Input()
  public set mode(value: LandingPageLayoutComponentCustomElement['mode']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.mode = value;
    });
  }
  public get mode(): LandingPageLayoutComponentCustomElement['mode'] {
    return this.nativeElement.mode;
  }

  /** Controls the horizontal alignment of the header content: `center` (default) or `left`. */
  @Input()
  public set alignment(value: LandingPageLayoutComponentCustomElement['alignment']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.alignment = value;
    });
  }
  public get alignment(): LandingPageLayoutComponentCustomElement['alignment'] {
    return this.nativeElement.alignment;
  }

  /** Controls the maximum width of the content area: `normal` (default) or `wide`. */
  @Input()
  public set size(value: LandingPageLayoutComponentCustomElement['size']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.size = value;
    });
  }
  public get size(): LandingPageLayoutComponentCustomElement['size'] {
    return this.nativeElement.size;
  }

  /** URL of the background image to use on large screens (>= 769px). */
  @Input()
  public set imageUrlLarge(value: LandingPageLayoutComponentCustomElement['imageUrlLarge']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.imageUrlLarge = value;
    });
  }
  public get imageUrlLarge(): LandingPageLayoutComponentCustomElement['imageUrlLarge'] {
    return this.nativeElement.imageUrlLarge;
  }

  /** URL of the background image to use on small screens (<= 768px). */
  @Input()
  public set imageUrlSmall(value: LandingPageLayoutComponentCustomElement['imageUrlSmall']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.imageUrlSmall = value;
    });
  }
  public get imageUrlSmall(): LandingPageLayoutComponentCustomElement['imageUrlSmall'] {
    return this.nativeElement.imageUrlSmall;
  }

  constructor() {
    defineLandingPageLayoutComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
