// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineLandingPageLayoutComponent } from '@tylertech/forge-extended';

import { LandingPageLayoutComponent } from './landing-page-layout.component';

@NgModule({
  imports: [CommonModule],
  declarations: [LandingPageLayoutComponent],
  exports: [LandingPageLayoutComponent]
})
export class ForgeExtendedLandingPageLayoutModule {
  constructor() {
    defineLandingPageLayoutComponent();
  }
}
