// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiModalComponent } from '@tylertech/forge-extended';

import { AiModalComponent } from './ai-modal.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiModalComponent],
  exports: [AiModalComponent]
})
export class ForgeExtendedAiModalModule {
  constructor() {
    defineAiModalComponent();
  }
}
