/**
 * Dependency-free color math for the theme editor.
 *
 * The operations here mirror the chroma-js calls that Tyler's
 * `forge-theme-generator` uses to derive a Forge palette, so a palette generated
 * here matches one generated by the official tool:
 *
 *   - `brighten`/`darken`         CIELab lightness shifts of 18 per unit (chroma's `Kn`)
 *   - `tint`/`shade`              mix toward white/black in linear-light RGB (chroma's `lrgb`)
 *   - `scaleOklch`                `chroma.scale(...).mode('oklch')`
 *   - `contrast`                  WCAG 2.x contrast ratio
 */

/** An sRGB color as `[red, green, blue, alpha]`, channels 0-255 and alpha 0-1. */
export type Rgba = [number, number, number, number];

/** A CIELab color as `[lightness, a, b]`. */
export type Lab = [number, number, number];

/** An OkLCh color as `[lightness, chroma, hue]`. Hue is `NaN` for neutral colors. */
export type Oklch = [number, number, number];

/** chroma-js uses `Kn = 18` as the Lab lightness step for brighten/darken. */
export const LAB_KN = 18;

// D65 white point, matching chroma-js.
const XN = 0.95047;
const YN = 1;
const ZN = 1.08883;
const LAB_T0 = 4 / 29;
const LAB_T1 = 6 / 29;
const LAB_T2 = 3 * LAB_T1 * LAB_T1;
const LAB_T3 = LAB_T1 * LAB_T1 * LAB_T1;

const clamp = (value: number, low: number, high: number): number => (value < low ? low : value > high ? high : value);

const clamp255 = (value: number): number => clamp(Math.round(value), 0, 255);

const srgbToLinear = (channel: number): number => {
  const value = channel / 255;
  return value <= 0.04045 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
};

const linearToSrgb = (value: number): number =>
  255 * (value <= 0.0031308 ? 12.92 * value : 1.055 * Math.pow(value, 1 / 2.4) - 0.055);

const labF = (t: number): number => (t > LAB_T3 ? Math.cbrt(t) : t / LAB_T2 + LAB_T0);

const labFInv = (t: number): number => (t > LAB_T1 ? t * t * t : LAB_T2 * (t - LAB_T0));

/**
 * Parses a CSS color string (hex, `rgb()`, `rgba()`, `white`, `black`,
 * `transparent`) or a channel array into an {@link Rgba} tuple.
 * @param input The value to parse.
 * @returns The parsed color, or `null` when the value is not a color this
 * editor understands.
 */
export function parseColor(input: string | number[] | null | undefined): Rgba | null {
  if (Array.isArray(input)) {
    if (input.length < 3) {
      return null;
    }
    return [clamp255(input[0]), clamp255(input[1]), clamp255(input[2]), input[3] ?? 1];
  }
  if (typeof input !== 'string') {
    return null;
  }

  const value = input.trim().toLowerCase();
  if (value === 'white') {
    return [255, 255, 255, 1];
  }
  if (value === 'black') {
    return [0, 0, 0, 1];
  }
  if (value === 'transparent') {
    return [0, 0, 0, 0];
  }

  if (value.startsWith('#')) {
    return parseHex(value.slice(1));
  }

  const match = /^rgba?\(([^)]+)\)$/.exec(value);
  if (match) {
    return parseRgbFunction(match[1]);
  }
  return null;
}

function parseHex(digits: string): Rgba | null {
  const isShort = digits.length === 3 || digits.length === 4;
  const isLong = digits.length === 6 || digits.length === 8;
  if (!isShort && !isLong) {
    return null;
  }

  const channels: number[] = [];
  if (isShort) {
    for (const digit of digits.split('')) {
      channels.push(parseInt(digit + digit, 16));
    }
  } else {
    for (let i = 0; i < digits.length; i += 2) {
      channels.push(parseInt(digits.slice(i, i + 2), 16));
    }
  }
  if (channels.some(Number.isNaN)) {
    return null;
  }
  const alpha = channels.length === 4 ? channels[3] / 255 : 1;
  return [channels[0], channels[1], channels[2], alpha];
}

function parseRgbFunction(body: string): Rgba | null {
  const parts = body.split(/[,\s/]+/).filter(Boolean);
  if (parts.length < 3) {
    return null;
  }
  const toNumber = (text: string, scale: number): number =>
    text.endsWith('%') ? (parseFloat(text) / 100) * scale : parseFloat(text);

  const rgb = parts.slice(0, 3).map(part => toNumber(part, 255));
  if (rgb.some(Number.isNaN)) {
    return null;
  }
  const alpha = parts[3] === undefined ? 1 : clamp(toNumber(parts[3], 1), 0, 1);
  return [clamp255(rgb[0]), clamp255(rgb[1]), clamp255(rgb[2]), alpha];
}

/**
 * Indicates whether a value is a color this editor understands.
 * @param input The value to test.
 */
export function isValidColor(input: string | number[] | null | undefined): boolean {
  return parseColor(input) !== null;
}

/**
 * Formats a color as `#rrggbb`, discarding alpha.
 * @param rgba The color to format.
 */
export function toHex(rgba: Rgba): string {
  return '#' + [rgba[0], rgba[1], rgba[2]].map(channel => clamp255(channel).toString(16).padStart(2, '0')).join('');
}

/**
 * Formats a color as `rgba(r, g, b, a)` when translucent and `#rrggbb` otherwise.
 * @param rgba The color to format.
 */
export function toCssColor(rgba: Rgba): string {
  const alpha = rgba[3] ?? 1;
  if (alpha >= 1) {
    return toHex(rgba);
  }
  return `rgba(${clamp255(rgba[0])}, ${clamp255(rgba[1])}, ${clamp255(rgba[2])}, ${+alpha.toFixed(4)})`;
}

/**
 * Converts sRGB to CIELab.
 * @param rgba The color to convert.
 */
export function rgbToLab(rgba: Rgba): Lab {
  const r = srgbToLinear(rgba[0]);
  const g = srgbToLinear(rgba[1]);
  const b = srgbToLinear(rgba[2]);
  const x = labF((0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / XN);
  const y = labF((0.2126729 * r + 0.7151522 * g + 0.072175 * b) / YN);
  const z = labF((0.0193339 * r + 0.119192 * g + 0.9503041 * b) / ZN);
  return [116 * y - 16, 500 * (x - y), 200 * (y - z)];
}

/**
 * Converts CIELab to sRGB, clamping out-of-gamut results.
 * @param lab The color to convert.
 */
export function labToRgb(lab: Lab): Rgba {
  const [lightness, a, b] = lab;
  const y = (lightness + 16) / 116;
  const x = Number.isNaN(a) ? y : y + a / 500;
  const z = Number.isNaN(b) ? y : y - b / 200;
  const X = XN * labFInv(x);
  const Y = YN * labFInv(y);
  const Z = ZN * labFInv(z);
  const red = 3.2404542 * X - 1.5371385 * Y - 0.4985314 * Z;
  const green = -0.969266 * X + 1.8760108 * Y + 0.041556 * Z;
  const blue = 0.0556434 * X - 0.2040259 * Y + 1.0572252 * Z;
  return [clamp255(linearToSrgb(red)), clamp255(linearToSrgb(green)), clamp255(linearToSrgb(blue)), 1];
}

function rgbToOklab(rgba: Rgba): Lab {
  const r = srgbToLinear(rgba[0]);
  const g = srgbToLinear(rgba[1]);
  const b = srgbToLinear(rgba[2]);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s
  ];
}

function oklabToRgb(oklab: Lab): Rgba {
  const [lightness, a, b] = oklab;
  const l = Math.pow(lightness + 0.3963377774 * a + 0.2158037573 * b, 3);
  const m = Math.pow(lightness - 0.1055613458 * a - 0.0638541728 * b, 3);
  const s = Math.pow(lightness - 0.0894841775 * a - 1.291485548 * b, 3);
  const red = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  const green = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  const blue = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  return [clamp255(linearToSrgb(red)), clamp255(linearToSrgb(green)), clamp255(linearToSrgb(blue)), 1];
}

/**
 * Converts sRGB to OkLCh. A fully neutral color gets a `NaN` hue so that
 * interpolation does not invent one.
 * @param rgba The color to convert.
 */
export function rgbToOklch(rgba: Rgba): Oklch {
  const [lightness, a, b] = rgbToOklab(rgba);
  const chroma = Math.sqrt(a * a + b * b);
  const hue = chroma < 1e-7 ? NaN : ((Math.atan2(b, a) * 180) / Math.PI + 360) % 360;
  return [lightness, chroma, hue];
}

/**
 * Converts OkLCh to sRGB.
 * @param oklch The color to convert.
 */
export function oklchToRgb(oklch: Oklch): Rgba {
  const [lightness, chroma, hue] = oklch;
  if (Number.isNaN(hue)) {
    return oklabToRgb([lightness, 0, 0]);
  }
  const radians = (hue * Math.PI) / 180;
  return oklabToRgb([lightness, chroma * Math.cos(radians), chroma * Math.sin(radians)]);
}

/**
 * chroma's `.brighten(amount)` — shifts CIELab lightness by `amount * 18`.
 * @param color The color to brighten.
 * @param amount The number of Lab lightness steps.
 */
export function brighten(color: Rgba, amount = 1): Rgba {
  const lab = rgbToLab(color);
  lab[0] += LAB_KN * amount;
  return labToRgb(lab);
}

/**
 * chroma's `.darken(amount)`.
 * @param color The color to darken.
 * @param amount The number of Lab lightness steps.
 */
export function darken(color: Rgba, amount = 1): Rgba {
  return brighten(color, -amount);
}

/**
 * Sets CIELab lightness to an absolute value, optionally damping chroma toward grey.
 * @param color The color to adjust.
 * @param lightness The target Lab lightness, 0-100.
 * @param chromaScale A multiplier applied to the `a`/`b` channels.
 */
export function withLightness(color: Rgba, lightness: number, chromaScale = 1): Rgba {
  const lab = rgbToLab(color);
  return labToRgb([clamp(lightness, 0, 100), lab[1] * chromaScale, lab[2] * chromaScale]);
}

/**
 * Mixes two colors in linear-light RGB — chroma's `lrgb` interpolation.
 * @param from The starting color.
 * @param to The ending color.
 * @param fraction How far to move toward `to`, 0-1.
 */
export function mixLrgb(from: Rgba, to: Rgba, fraction = 0.5): Rgba {
  const channel = (index: number): number =>
    Math.sqrt(from[index] * from[index] * (1 - fraction) + to[index] * to[index] * fraction);
  return [clamp255(channel(0)), clamp255(channel(1)), clamp255(channel(2)), 1];
}

const WHITE: Rgba = [255, 255, 255, 1];
const BLACK: Rgba = [0, 0, 0, 1];

/**
 * chroma's `.tint(fraction)` — mixes toward white in linear-light RGB.
 * @param color The color to tint.
 * @param fraction How far to move toward white, 0-1.
 */
export function tint(color: Rgba, fraction = 0.5): Rgba {
  return mixLrgb(color, WHITE, fraction);
}

/**
 * chroma's `.shade(fraction)` — mixes toward black in linear-light RGB.
 * @param color The color to shade.
 * @param fraction How far to move toward black, 0-1.
 */
export function shade(color: Rgba, fraction = 0.5): Rgba {
  return mixLrgb(color, BLACK, fraction);
}

/**
 * `chroma.scale([from, to]).mode('oklch').colors(count)` — evenly spaced samples
 * inclusive of both endpoints, interpolated in OkLCh with shortest-path hue.
 * @param from The starting color.
 * @param to The ending color.
 * @param count How many samples to produce.
 */
export function scaleOklch(from: Rgba, to: Rgba, count: number): Rgba[] {
  const start = rgbToOklch(from);
  const end = rgbToOklch(to);
  const out: Rgba[] = [];
  for (let i = 0; i < count; i++) {
    const t = count === 1 ? 0 : i / (count - 1);
    const lightness = start[0] + (end[0] - start[0]) * t;
    const chroma = start[1] + (end[1] - start[1]) * t;
    out.push(oklchToRgb([lightness, chroma, interpolateHue(start[2], end[2], t)]));
  }
  return out;
}

function interpolateHue(from: number, to: number, t: number): number {
  if (Number.isNaN(from) && Number.isNaN(to)) {
    return NaN;
  }
  if (Number.isNaN(from)) {
    return to;
  }
  if (Number.isNaN(to)) {
    return from;
  }
  let delta = to - from;
  if (delta > 180) {
    delta -= 360;
  }
  if (delta < -180) {
    delta += 360;
  }
  return (from + delta * t + 360) % 360;
}

/**
 * WCAG 2.x relative luminance.
 * @param color The color to measure.
 */
export function luminance(color: Rgba): number {
  return 0.2126 * srgbToLinear(color[0]) + 0.7152 * srgbToLinear(color[1]) + 0.0722 * srgbToLinear(color[2]);
}

/**
 * WCAG 2.x contrast ratio, always at least 1.
 * @param a The first color.
 * @param b The second color.
 */
export function contrast(a: Rgba, b: Rgba): number {
  const luminanceA = luminance(a);
  const luminanceB = luminance(b);
  return (Math.max(luminanceA, luminanceB) + 0.05) / (Math.min(luminanceA, luminanceB) + 0.05);
}

/**
 * WCAG 2.x contrast ratio between two CSS color strings.
 * @param a The first color.
 * @param b The second color.
 * @returns The ratio, or `null` when either value is not a parseable color.
 */
export function contrastOf(a: string, b: string): number | null {
  const colorA = parseColor(a);
  const colorB = parseColor(b);
  if (!colorA || !colorB) {
    return null;
  }
  return contrast(colorA, colorB);
}

/**
 * Flattens a translucent color onto an opaque backdrop so that alpha-bearing
 * tokens (Forge's `text-*` scale) can be measured for contrast.
 * @param color The foreground color.
 * @param backdrop The opaque color behind it.
 */
export function flatten(color: Rgba, backdrop: Rgba): Rgba {
  const alpha = color[3] ?? 1;
  if (alpha >= 1) {
    return [color[0], color[1], color[2], 1];
  }
  return [
    clamp255(color[0] * alpha + backdrop[0] * (1 - alpha)),
    clamp255(color[1] * alpha + backdrop[1] * (1 - alpha)),
    clamp255(color[2] * alpha + backdrop[2] * (1 - alpha)),
    1
  ];
}
