// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiFilePickerComponent } from '@tylertech/forge-extended';

import { ForgeAiFilePickerComponent } from './forge-ai-file-picker.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiFilePickerComponent],
  exports: [ForgeAiFilePickerComponent]
})
export class ForgeExtendedForgeAiFilePickerModule {
  constructor() {
    defineForgeAiFilePickerComponent();
  }
}
