// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ForgeAiFilePickerComponent as ForgeAiFilePickerComponentCustomElement,
  defineForgeAiFilePickerComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-file-picker',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ForgeAiFilePickerComponent {
  protected elementRef = inject<ElementRef<ForgeAiFilePickerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-file-picker element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The variant of the file picker button. */
  @Input()
  public set variant(value: ForgeAiFilePickerComponentCustomElement['variant']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.variant = value;
    });
  }
  public get variant(): ForgeAiFilePickerComponentCustomElement['variant'] {
    return this.nativeElement.variant;
  }

  /** Whether the file picker is disabled. */
  @Input({ transform: booleanAttribute })
  public set disabled(value: ForgeAiFilePickerComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): ForgeAiFilePickerComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Accepted file types (comma-separated MIME types or extensions). */
  @Input()
  public set accept(value: ForgeAiFilePickerComponentCustomElement['accept']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.accept = value;
    });
  }
  public get accept(): ForgeAiFilePickerComponentCustomElement['accept'] {
    return this.nativeElement.accept;
  }

  /** Whether to allow multiple file selection. */
  @Input({ transform: booleanAttribute })
  public set multiple(value: ForgeAiFilePickerComponentCustomElement['multiple']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.multiple = value;
    });
  }
  public get multiple(): ForgeAiFilePickerComponentCustomElement['multiple'] {
    return this.nativeElement.multiple;
  }

  constructor() {
    defineForgeAiFilePickerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
