// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core'; 
import { defineBusyIndicatorElementComponent } from '@tylertech/forge-extended';

import { BusyIndicatorElement } from './busy-indicator-element.component';

@NgModule({
	imports: [CommonModule],
	declarations: [BusyIndicatorElement],
	exports: [BusyIndicatorElement]
})
export class ForgeExtendedBusyIndicatorElementProxyModule {
	constructor() {
		defineBusyIndicatorElementComponent();
	}
}