// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureBoldComponent } from '@tylertech/forge-extended';

import { RichTextFeatureBoldComponent } from './rich-text-feature-bold.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureBoldComponent],
  exports: [RichTextFeatureBoldComponent]
})
export class ForgeExtendedRichTextFeatureBoldModule {
  constructor() {
    defineRichTextFeatureBoldComponent();
  }
}
