// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureBoldComponent as RichTextFeatureBoldComponentCustomElement,
  defineRichTextFeatureBoldComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-bold',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureBoldComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureBoldComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-bold element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the bold button. */
  @Input()
  public set label(value: RichTextFeatureBoldComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RichTextFeatureBoldComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RichTextFeatureBoldComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureBoldComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
