packages:
  - packages/*
catalog:
  '@custom-elements-manifest/analyzer': 0.10.4
  '@esm-bundle/chai': 4.3.4-fix.0
  '@open-wc/testing': 4.0.0
  '@storybook/addon-a11y': 8.4.7
  '@storybook/addon-essentials': 8.4.7
  '@storybook/addon-links': 8.4.7
  '@storybook/addon-measure': 8.4.7
  '@storybook/addon-themes': 8.4.7
  '@storybook/addon-viewport': 8.4.7
  '@storybook/blocks': 8.4.7
  '@storybook/preview-api': 8.4.7
  '@storybook/test': 8.4.7
  '@storybook/theming': 8.4.7
  '@storybook/web-components': 8.4.7
  '@storybook/web-components-vite': 8.4.7
  '@tylertech-eslint/eslint-plugin': 2.1.0
  '@tylertech/forge': 3.4.1
  '@tylertech/forge-core': 3.1.0
  '@tylertech/stylelint-rules': 5.1.0
  '@tylertech/tyler-icons': 1.18.1
  '@types/mocha': 10.0.10
  '@types/node': 22.10.5
  '@web/dev-server-esbuild': 1.0.3
  '@web/test-runner': 0.19.0
  '@web/test-runner-commands': 0.9.0
  '@web/test-runner-junit-reporter': 0.7.2
  '@web/test-runner-playwright': 0.11.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.2.1
  glob: 11.0.0
  lit: 3.2.1
  lit-analyzer: 2.0.3
  postcss-lit: 1.2.0
  prettier: 3.4.2
  remark-gfm: 4.0.0
  rimraf: 6.0.0
  sass: 1.83.1
  sinon: 19.0.2
  storybook: 8.4.7
  storybook-dark-mode: 4.0.2
  stylelint: 16.12.0
  stylelint-config-standard: 36.0.1
  tslib: 2.8.1
  vite: 6.0.7
  vite-plugin-dts: 4.4.0
  vite-tsconfig-paths: 5.1.4
