packages:
  - packages/*
catalog:
  '@custom-elements-manifest/analyzer': 0.10.4
  '@esm-bundle/chai': 4.3.4-fix.0
  '@open-wc/testing': 4.0.0
  '@storybook/addon-a11y': 8.5.4
  '@storybook/addon-essentials': 8.5.4
  '@storybook/addon-links': 8.5.4
  '@storybook/addon-measure': 8.5.4
  '@storybook/addon-themes': 8.5.4
  '@storybook/addon-viewport': 8.5.4
  '@storybook/blocks': 8.5.4
  '@storybook/preview-api': 8.5.4
  '@storybook/test': 8.5.4
  '@storybook/theming': 8.5.4
  '@storybook/web-components': 8.5.4
  '@storybook/web-components-vite': 8.5.4
  '@tylertech-eslint/eslint-plugin': 2.1.0
  '@tylertech/forge': 3.6.3
  '@tylertech/forge-core': 3.1.0
  '@tylertech/stylelint-rules': 5.1.1
  '@tylertech/tyler-icons': 1.18.1
  '@types/mocha': 10.0.10
  '@types/node': 22.13.1
  '@types/sinon': 17.0.3
  '@typescript-eslint/eslint-plugin': 7.18.0
  '@web/dev-server-esbuild': 1.0.3
  '@web/test-runner': 0.19.0
  '@web/test-runner-commands': 0.9.0
  '@web/test-runner-junit-reporter': 0.7.2
  '@web/test-runner-playwright': 0.11.0
  eslint: 8.57.1
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.2.3
  glob: 11.0.1
  lit: 3.2.1
  lit-analyzer: 2.0.3
  plop: 4.0.1
  postcss-lit: 1.2.0
  prettier: 3.5.0
  remark-gfm: 4.0.1
  rimraf: 6.0.1
  sass: 1.84.0
  sinon: 19.0.2
  storybook: 8.5.4
  storybook-dark-mode: 4.0.2
  stylelint: 16.14.1
  stylelint-config-standard: 37.0.0
  tslib: 2.8.1
  vite: 6.1.0
  vite-plugin-dts: 4.5.0
  vite-tsconfig-paths: 5.1.4
