packages:
  - packages/*

catalog:
  '@custom-elements-manifest/analyzer': 0.10.4
  '@esm-bundle/chai': 4.3.4-fix.0
  '@open-wc/testing': 4.0.0
  '@storybook/addon-a11y': 9.0.14
  '@storybook/addon-docs': 9.0.14
  '@storybook/addon-links': 9.0.14
  '@storybook/addon-themes': 9.0.14
  '@storybook/web-components-vite': 9.0.14
  '@tylertech-eslint/eslint-plugin': 3.0.0
  '@tylertech/forge': 3.12.1
  '@tylertech/forge-core': 3.2.1
  '@tylertech/stylelint-rules': 5.1.2
  '@tylertech/tyler-icons': 2.0.4
  '@types/mocha': 10.0.10
  '@types/node': 22.15.33
  '@types/sinon': 17.0.4
  '@vueless/storybook-dark-mode': 9.0.5
  '@web/dev-server-esbuild': 1.0.4
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.20.2
  '@web/test-runner-commands': 0.9.0
  '@web/test-runner-junit-reporter': 0.8.0
  '@web/test-runner-playwright': 0.11.1
  eslint: 9.30.0
  eslint-config-prettier: 10.1.5
  eslint-plugin-prettier: 5.5.1
  glob: 11.1.0
  lit: 3.3.0
  lit-analyzer: 2.0.3
  plop: 4.0.1
  postcss-lit: 1.2.0
  prettier: 3.6.2
  remark-gfm: 4.0.1
  rimraf: 6.0.1
  sass: 1.89.2
  sinon: 21.0.0
  storybook: 9.0.14
  stylelint: 16.21.0
  stylelint-config-standard: 38.0.0
  tslib: 2.8.1
  vite: 7.0.8
  vite-plugin-dts: 4.5.4
  vite-tsconfig-paths: 5.1.4
