// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureHeadingComponent } from '@tylertech/forge-extended';

import { RichTextFeatureHeadingComponent } from './rich-text-feature-heading.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureHeadingComponent],
  exports: [RichTextFeatureHeadingComponent]
})
export class ForgeExtendedRichTextFeatureHeadingModule {
  constructor() {
    defineRichTextFeatureHeadingComponent();
  }
}
