// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureHeadingComponent as RichTextFeatureHeadingComponentCustomElement,
  defineRichTextFeatureHeadingComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-heading',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureHeadingComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureHeadingComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-heading element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the heading 1 button. */
  @Input()
  public set h1Label(value: RichTextFeatureHeadingComponentCustomElement['h1Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h1Label = value;
    });
  }
  public get h1Label(): RichTextFeatureHeadingComponentCustomElement['h1Label'] {
    return this.nativeElement.h1Label;
  }

  /** The accessible label for the heading 2 button. */
  @Input()
  public set h2Label(value: RichTextFeatureHeadingComponentCustomElement['h2Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h2Label = value;
    });
  }
  public get h2Label(): RichTextFeatureHeadingComponentCustomElement['h2Label'] {
    return this.nativeElement.h2Label;
  }

  /** The accessible label for the heading 3 button. */
  @Input()
  public set h3Label(value: RichTextFeatureHeadingComponentCustomElement['h3Label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.h3Label = value;
    });
  }
  public get h3Label(): RichTextFeatureHeadingComponentCustomElement['h3Label'] {
    return this.nativeElement.h3Label;
  }

  public get extensions(): RichTextFeatureHeadingComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureHeadingComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
