// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiPromptComponent } from '@tylertech/forge-extended';

import { AiPromptComponent } from './ai-prompt.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiPromptComponent],
  exports: [AiPromptComponent]
})
export class ForgeExtendedAiPromptModule {
  constructor() {
    defineAiPromptComponent();
  }
}
