// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiOverlayComponent } from '@tylertech/forge-extended';

import { ForgeAiOverlayComponent } from './forge-ai-overlay.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiOverlayComponent],
  exports: [ForgeAiOverlayComponent]
})
export class ForgeExtendedForgeAiOverlayModule {
  constructor() {
    defineForgeAiOverlayComponent();
  }
}
