// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiActionsToolbarComponent } from '@tylertech/forge-extended';

import { AiActionsToolbarComponent } from './ai-actions-toolbar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiActionsToolbarComponent],
  exports: [AiActionsToolbarComponent]
})
export class ForgeExtendedAiActionsToolbarModule {
  constructor() {
    defineAiActionsToolbarComponent();
  }
}
