// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureDividerComponent as RichTextFeatureDividerComponentCustomElement,
  defineRichTextFeatureDividerComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-feature-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureDividerComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureDividerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-feature-divider element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineRichTextFeatureDividerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
