// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureDividerComponent } from '@tylertech/forge-extended';

import { RichTextFeatureDividerComponent } from './rich-text-feature-divider.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureDividerComponent],
  exports: [RichTextFeatureDividerComponent]
})
export class ForgeExtendedRichTextFeatureDividerModule {
  constructor() {
    defineRichTextFeatureDividerComponent();
  }
}
