// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiSidebarComponent } from '@tylertech/forge-extended';

import { AiSidebarComponent } from './ai-sidebar.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiSidebarComponent],
  exports: [AiSidebarComponent]
})
export class ForgeExtendedAiSidebarModule {
  constructor() {
    defineAiSidebarComponent();
  }
}
