// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppLinkComponent } from '@tylertech/forge-extended';

import { AppLinkComponent } from './app-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppLinkComponent],
  exports: [AppLinkComponent]
})
export class ForgeExtendedAppLinkModule {
  constructor() {
    defineAppLinkComponent();
  }
}
