// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import { AppLinkComponent as AppLinkComponentCustomElement, defineAppLinkComponent } from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-app-link',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AppLinkComponent {
  protected elementRef = inject<ElementRef<AppLinkComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-app-link element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAppLinkComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
