// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureAlignComponent as RichTextFeatureAlignComponentCustomElement,
  defineRichTextFeatureAlignComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-align',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureAlignComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureAlignComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-align element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the left align button. */
  @Input()
  public set leftLabel(value: RichTextFeatureAlignComponentCustomElement['leftLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.leftLabel = value;
    });
  }
  public get leftLabel(): RichTextFeatureAlignComponentCustomElement['leftLabel'] {
    return this.nativeElement.leftLabel;
  }

  /** The accessible label for the center align button. */
  @Input()
  public set centerLabel(value: RichTextFeatureAlignComponentCustomElement['centerLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.centerLabel = value;
    });
  }
  public get centerLabel(): RichTextFeatureAlignComponentCustomElement['centerLabel'] {
    return this.nativeElement.centerLabel;
  }

  /** The accessible label for the right align button. */
  @Input()
  public set rightLabel(value: RichTextFeatureAlignComponentCustomElement['rightLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.rightLabel = value;
    });
  }
  public get rightLabel(): RichTextFeatureAlignComponentCustomElement['rightLabel'] {
    return this.nativeElement.rightLabel;
  }

  /** The accessible label for the justify button. */
  @Input()
  public set justifyLabel(value: RichTextFeatureAlignComponentCustomElement['justifyLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.justifyLabel = value;
    });
  }
  public get justifyLabel(): RichTextFeatureAlignComponentCustomElement['justifyLabel'] {
    return this.nativeElement.justifyLabel;
  }

  public get extensions(): RichTextFeatureAlignComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureAlignComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
