// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureAlignComponent } from '@tylertech/forge-extended';

import { RichTextFeatureAlignComponent } from './rich-text-feature-align.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureAlignComponent],
  exports: [RichTextFeatureAlignComponent]
})
export class ForgeExtendedRichTextFeatureAlignModule {
  constructor() {
    defineRichTextFeatureAlignComponent();
  }
}
