// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureUndoRedoComponent as RichTextFeatureUndoRedoComponentCustomElement,
  defineRichTextFeatureUndoRedoComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-undo-redo',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureUndoRedoComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureUndoRedoComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-undo-redo element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the undo button. */
  @Input()
  public set undoLabel(value: RichTextFeatureUndoRedoComponentCustomElement['undoLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.undoLabel = value;
    });
  }
  public get undoLabel(): RichTextFeatureUndoRedoComponentCustomElement['undoLabel'] {
    return this.nativeElement.undoLabel;
  }

  /** The accessible label for the redo button. */
  @Input()
  public set redoLabel(value: RichTextFeatureUndoRedoComponentCustomElement['redoLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.redoLabel = value;
    });
  }
  public get redoLabel(): RichTextFeatureUndoRedoComponentCustomElement['redoLabel'] {
    return this.nativeElement.redoLabel;
  }

  public get extensions(): RichTextFeatureUndoRedoComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureUndoRedoComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
