// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  PromptButtonComponent as PromptButtonComponentCustomElement,
  definePromptButtonComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-prompt-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class PromptButtonComponent {
  protected elementRef = inject<ElementRef<PromptButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-prompt-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the button is disabled */
  @Input({ transform: booleanAttribute })
  public set disabled(value: PromptButtonComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): PromptButtonComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  constructor() {
    definePromptButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
