// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { definePromptButtonComponent } from '@tylertech/forge-extended';

import { PromptButtonComponent } from './prompt-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [PromptButtonComponent],
  exports: [PromptButtonComponent]
})
export class ForgeExtendedPromptButtonModule {
  constructor() {
    definePromptButtonComponent();
  }
}
