// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ContentScaffoldComponent as ContentScaffoldComponentCustomElement,
  defineContentScaffoldComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-content-scaffold',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ContentScaffoldComponent {
  protected elementRef = inject<ElementRef<ContentScaffoldComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-content-scaffold element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** When true, enables the full-width header mode using the `header` slot instead of the multi-slot layout. */
  @Input({ transform: booleanAttribute })
  public set fullWidthHeader(value: ContentScaffoldComponentCustomElement['fullWidthHeader']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fullWidthHeader = value;
    });
  }
  public get fullWidthHeader(): ContentScaffoldComponentCustomElement['fullWidthHeader'] {
    return this.nativeElement.fullWidthHeader;
  }

  /** When true, enables the full-width footer mode using the `footer` slot instead of the multi-slot layout. */
  @Input({ transform: booleanAttribute })
  public set fullWidthFooter(value: ContentScaffoldComponentCustomElement['fullWidthFooter']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fullWidthFooter = value;
    });
  }
  public get fullWidthFooter(): ContentScaffoldComponentCustomElement['fullWidthFooter'] {
    return this.nativeElement.fullWidthFooter;
  }

  constructor() {
    defineContentScaffoldComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
