// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiVoiceInputComponent as AiVoiceInputComponentCustomElement,
  defineAiVoiceInputComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-voice-input',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiVoiceInputComponent {
  protected elementRef = inject<ElementRef<AiVoiceInputComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-voice-input element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAiVoiceInputComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
