// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiVoiceInputComponent } from '@tylertech/forge-extended';

import { AiVoiceInputComponent } from './ai-voice-input.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiVoiceInputComponent],
  exports: [AiVoiceInputComponent]
})
export class ForgeExtendedAiVoiceInputModule {
  constructor() {
    defineAiVoiceInputComponent();
  }
}
