// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureLinkComponent as RichTextFeatureLinkComponentCustomElement,
  defineRichTextFeatureLinkComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-link',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureLinkComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureLinkComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-link element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the link button. */
  @Input()
  public set label(value: RichTextFeatureLinkComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RichTextFeatureLinkComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  /** Whether to validate URL format before applying. When enabled, shows error messages for invalid URLs. */
  @Input({ transform: booleanAttribute })
  public set validateUrls(value: RichTextFeatureLinkComponentCustomElement['validateUrls']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.validateUrls = value;
    });
  }
  public get validateUrls(): RichTextFeatureLinkComponentCustomElement['validateUrls'] {
    return this.nativeElement.validateUrls;
  }

  /** Whether to automatically add https:// protocol if missing from the URL. */
  @Input({ transform: booleanAttribute })
  public set autoProtocol(value: RichTextFeatureLinkComponentCustomElement['autoProtocol']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.autoProtocol = value;
    });
  }
  public get autoProtocol(): RichTextFeatureLinkComponentCustomElement['autoProtocol'] {
    return this.nativeElement.autoProtocol;
  }

  public get extensions(): RichTextFeatureLinkComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureLinkComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
