// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppLauncherComponent } from '@tylertech/forge-extended';

import { AppLauncherComponent } from './app-launcher.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppLauncherComponent],
  exports: [AppLauncherComponent]
})
export class ForgeExtendedAppLauncherModule {
  constructor() {
    defineAppLauncherComponent();
  }
}
