// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiDropdownMenuItemComponent } from '@tylertech/forge-extended';

import { ForgeAiDropdownMenuItemComponent } from './forge-ai-dropdown-menu-item.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiDropdownMenuItemComponent],
  exports: [ForgeAiDropdownMenuItemComponent]
})
export class ForgeExtendedForgeAiDropdownMenuItemModule {
  constructor() {
    defineForgeAiDropdownMenuItemComponent();
  }
}
