// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiEmptyStateComponent as AiEmptyStateComponentCustomElement,
  defineAiEmptyStateComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-empty-state',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiEmptyStateComponent {
  protected elementRef = inject<ElementRef<AiEmptyStateComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-empty-state element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAiEmptyStateComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
