// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiEmptyStateComponent } from '@tylertech/forge-extended';

import { AiEmptyStateComponent } from './ai-empty-state.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiEmptyStateComponent],
  exports: [AiEmptyStateComponent]
})
export class ForgeExtendedAiEmptyStateModule {
  constructor() {
    defineAiEmptyStateComponent();
  }
}
