// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAppLayoutComponent } from '@tylertech/forge-extended';

import { AppLayoutComponent } from './app-layout.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AppLayoutComponent],
  exports: [AppLayoutComponent]
})
export class ForgeExtendedAppLayoutModule {
  constructor() {
    defineAppLayoutComponent();
  }
}
