// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineUserProfileComponent } from '@tylertech/forge-extended';

import { UserProfileComponent } from './user-profile.component';

@NgModule({
  imports: [CommonModule],
  declarations: [UserProfileComponent],
  exports: [UserProfileComponent]
})
export class ForgeExtendedUserProfileModule {
  constructor() {
    defineUserProfileComponent();
  }
}
