// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiChatHeaderComponent } from '@tylertech/forge-extended';

import { AiChatHeaderComponent } from './ai-chat-header.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiChatHeaderComponent],
  exports: [AiChatHeaderComponent]
})
export class ForgeExtendedAiChatHeaderModule {
  constructor() {
    defineAiChatHeaderComponent();
  }
}
