// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiEmbeddedChatComponent } from '@tylertech/forge-extended';

import { AiEmbeddedChatComponent } from './ai-embedded-chat.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiEmbeddedChatComponent],
  exports: [AiEmbeddedChatComponent]
})
export class ForgeExtendedAiEmbeddedChatModule {
  constructor() {
    defineAiEmbeddedChatComponent();
  }
}
