// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineQuantityFieldElementComponent } from '@tylertech/forge-extended';

import { QuantityFieldElement } from './quantity-field-element.component';

@NgModule({
  imports: [CommonModule],
  declarations: [QuantityFieldElement],
  exports: [QuantityFieldElement]
})
export class ForgeExtendedQuantityFieldElementModule {
  constructor() {
    defineQuantityFieldElementComponent();
  }
}
