// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input
} from '@angular/core';
import {
  ConfirmationDialogComponent as ConfirmationDialogComponentCustomElement,
  defineConfirmationDialogComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-confirmation-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ConfirmationDialogComponent {
  /** The forge-confirmation-dialog element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Indicates whether the confirmation dialog is open. */
  @Input({ transform: booleanAttribute })
  public set open(value: ConfirmationDialogComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): ConfirmationDialogComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** Indicates whether the confirmation dialog in a busy state */
  @Input({ transform: booleanAttribute })
  public set isBusy(value: ConfirmationDialogComponentCustomElement['isBusy']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.isBusy = value;
    });
  }
  public get isBusy(): ConfirmationDialogComponentCustomElement['isBusy'] {
    return this.nativeElement.isBusy;
  }

  /** Aria label of the busy indicator when loading */
  @Input()
  public set ariaLabelLoading(value: ConfirmationDialogComponentCustomElement['ariaLabelLoading']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.ariaLabelLoading = value;
    });
  }
  public get ariaLabelLoading(): ConfirmationDialogComponentCustomElement['ariaLabelLoading'] {
    return this.nativeElement.ariaLabelLoading;
  }

  constructor(
    changeDetectorRef: ChangeDetectorRef,
    protected elementRef: ElementRef<ConfirmationDialogComponentCustomElement>,
    protected zone: NgZone
  ) {
    defineConfirmationDialogComponent();
    changeDetectorRef.detach();
  }
}
