// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiDropdownMenuSeparatorComponent } from '@tylertech/forge-extended';

import { ForgeAiDropdownMenuSeparatorComponent } from './forge-ai-dropdown-menu-separator.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiDropdownMenuSeparatorComponent],
  exports: [ForgeAiDropdownMenuSeparatorComponent]
})
export class ForgeExtendedForgeAiDropdownMenuSeparatorModule {
  constructor() {
    defineForgeAiDropdownMenuSeparatorComponent();
  }
}
