// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiThreadsComponent } from '@tylertech/forge-extended';

import { AiThreadsComponent } from './ai-threads.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiThreadsComponent],
  exports: [AiThreadsComponent]
})
export class ForgeExtendedAiThreadsModule {
  constructor() {
    defineAiThreadsComponent();
  }
}
