// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiThreadsComponent as AiThreadsComponentCustomElement,
  defineAiThreadsComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-threads',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiThreadsComponent {
  protected elementRef = inject<ElementRef<AiThreadsComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-threads element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Array of threads to display in the navigation list */
  @Input()
  public set threads(value: AiThreadsComponentCustomElement['threads']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.threads = value;
    });
  }
  public get threads(): AiThreadsComponentCustomElement['threads'] {
    return this.nativeElement.threads;
  }

  constructor() {
    defineAiThreadsComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
