// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThemeShowcaseComponent } from '@tylertech/forge-extended';

import { ThemeShowcaseComponent } from './theme-showcase.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThemeShowcaseComponent],
  exports: [ThemeShowcaseComponent]
})
export class ForgeExtendedThemeShowcaseModule {
  constructor() {
    defineThemeShowcaseComponent();
  }
}
