// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ThemeShowcaseComponent as ThemeShowcaseComponentCustomElement,
  defineThemeShowcaseComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-theme-showcase',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ThemeShowcaseComponent {
  protected elementRef = inject<ElementRef<ThemeShowcaseComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-theme-showcase element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineThemeShowcaseComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
