// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ProgressTrackerComponent as ProgressTrackerComponentCustomElement,
  defineProgressTrackerComponent
} from '@tylertech/forge-extended';

/**
 * Displays progress through a sequence of steps or milestones, distinguishing completed from
 * incomplete steps. Steps that provide a description are interactive and dispatch an event when
 * selected so the consuming application can present the additional information, typically in a
 * dialog that it owns.
 */
@Component({
  selector: 'forge-progress-tracker',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ProgressTrackerComponent {
  protected elementRef = inject<ElementRef<ProgressTrackerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-progress-tracker element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The steps to display. Steps are rendered in the order provided. */
  @Input()
  public set steps(value: ProgressTrackerComponentCustomElement['steps']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.steps = value;
    });
  }
  public get steps(): ProgressTrackerComponentCustomElement['steps'] {
    return this.nativeElement.steps;
  }

  /** The layout orientation of the steps. */
  @Input()
  public set orientation(value: ProgressTrackerComponentCustomElement['orientation']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.orientation = value;
    });
  }
  public get orientation(): ProgressTrackerComponentCustomElement['orientation'] {
    return this.nativeElement.orientation;
  }

  /** The accessible status text announced for completed steps. */
  @Input()
  public set completedLabel(value: ProgressTrackerComponentCustomElement['completedLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.completedLabel = value;
    });
  }
  public get completedLabel(): ProgressTrackerComponentCustomElement['completedLabel'] {
    return this.nativeElement.completedLabel;
  }

  /** The accessible status text announced for incomplete steps. */
  @Input()
  public set incompleteLabel(value: ProgressTrackerComponentCustomElement['incompleteLabel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.incompleteLabel = value;
    });
  }
  public get incompleteLabel(): ProgressTrackerComponentCustomElement['incompleteLabel'] {
    return this.nativeElement.incompleteLabel;
  }

  constructor() {
    defineProgressTrackerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
