// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineProgressTrackerComponent } from '@tylertech/forge-extended';

import { ProgressTrackerComponent } from './progress-tracker.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ProgressTrackerComponent],
  exports: [ProgressTrackerComponent]
})
export class ForgeExtendedProgressTrackerModule {
  constructor() {
    defineProgressTrackerComponent();
  }
}
