// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiChainOfThoughtComponent } from '@tylertech/forge-extended';

import { AiChainOfThoughtComponent } from './ai-chain-of-thought.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiChainOfThoughtComponent],
  exports: [AiChainOfThoughtComponent]
})
export class ForgeExtendedAiChainOfThoughtModule {
  constructor() {
    defineAiChainOfThoughtComponent();
  }
}
