// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiChatWidgetComponent } from '@tylertech/forge-extended';

import { AiChatWidgetComponent } from './ai-chat-widget.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiChatWidgetComponent],
  exports: [AiChatWidgetComponent]
})
export class ForgeExtendedAiChatWidgetModule {
  constructor() {
    defineAiChatWidgetComponent();
  }
}
