// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiChatWidgetComponent as AiChatWidgetComponentCustomElement,
  defineAiChatWidgetComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-chat-widget',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiChatWidgetComponent {
  protected elementRef = inject<ElementRef<AiChatWidgetComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-chat-widget element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Indicates whether the dialog is open. */
  @Input({ transform: booleanAttribute })
  public set open(value: AiChatWidgetComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): AiChatWidgetComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /** Indicates whether the component is in its full size state. */
  @Input({ transform: booleanAttribute })
  public set fullsize(value: AiChatWidgetComponentCustomElement['fullsize']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.fullsize = value;
    });
  }
  public get fullsize(): AiChatWidgetComponentCustomElement['fullsize'] {
    return this.nativeElement.fullsize;
  }

  constructor() {
    defineAiChatWidgetComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
