// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiSidebarChatComponent } from '@tylertech/forge-extended';

import { AiSidebarChatComponent } from './ai-sidebar-chat.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiSidebarChatComponent],
  exports: [AiSidebarChatComponent]
})
export class ForgeExtendedAiSidebarChatModule {
  constructor() {
    defineAiSidebarChatComponent();
  }
}
