// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiFabComponent } from '@tylertech/forge-extended';

import { AiFabComponent } from './ai-fab.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiFabComponent],
  exports: [AiFabComponent]
})
export class ForgeExtendedAiFabModule {
  constructor() {
    defineAiFabComponent();
  }
}
