// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThoughtBaseComponent } from '@tylertech/forge-extended';

import { ThoughtBaseComponent } from './thought-base.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThoughtBaseComponent],
  exports: [ThoughtBaseComponent]
})
export class ForgeExtendedThoughtBaseModule {
  constructor() {
    defineThoughtBaseComponent();
  }
}
