// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ThoughtBaseComponent as ThoughtBaseComponentCustomElement,
  defineThoughtBaseComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-thought-base',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ThoughtBaseComponent {
  protected elementRef = inject<ElementRef<ThoughtBaseComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-thought-base element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The step number for this thought */
  @Input()
  public set step(value: ThoughtBaseComponentCustomElement['step']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.step = value;
    });
  }
  public get step(): ThoughtBaseComponentCustomElement['step'] {
    return this.nativeElement.step;
  }

  constructor() {
    defineThoughtBaseComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
