// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ForgeAiDropdownMenuItemGroupComponent as ForgeAiDropdownMenuItemGroupComponentCustomElement,
  defineForgeAiDropdownMenuItemGroupComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-dropdown-menu-item-group',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ForgeAiDropdownMenuItemGroupComponent {
  protected elementRef = inject<ElementRef<ForgeAiDropdownMenuItemGroupComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-dropdown-menu-item-group element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineForgeAiDropdownMenuItemGroupComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
