// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureStrikeComponent } from '@tylertech/forge-extended';

import { RichTextFeatureStrikeComponent } from './rich-text-feature-strike.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureStrikeComponent],
  exports: [RichTextFeatureStrikeComponent]
})
export class ForgeExtendedRichTextFeatureStrikeModule {
  constructor() {
    defineRichTextFeatureStrikeComponent();
  }
}
