// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureStrikeComponent as RichTextFeatureStrikeComponentCustomElement,
  defineRichTextFeatureStrikeComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-strike',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureStrikeComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureStrikeComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-strike element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the strikethrough button. */
  @Input()
  public set label(value: RichTextFeatureStrikeComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RichTextFeatureStrikeComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RichTextFeatureStrikeComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureStrikeComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
