// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import { AiIconComponent as AiIconComponentCustomElement, defineAiIconComponent } from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-icon',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiIconComponent {
  protected elementRef = inject<ElementRef<AiIconComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-icon element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAiIconComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
