// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiIconComponent } from '@tylertech/forge-extended';

import { AiIconComponent } from './ai-icon.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiIconComponent],
  exports: [AiIconComponent]
})
export class ForgeExtendedAiIconModule {
  constructor() {
    defineAiIconComponent();
  }
}
