// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import { AiIconComponent as AiIconComponentCustomElement, defineAiIconComponent } from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-icon',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiIconComponent {
  protected elementRef = inject<ElementRef<AiIconComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-icon element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether to display the icon with an outline */
  @Input({ transform: booleanAttribute })
  public set outline(value: AiIconComponentCustomElement['outline']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.outline = value;
    });
  }
  public get outline(): AiIconComponentCustomElement['outline'] {
    return this.nativeElement.outline;
  }

  constructor() {
    defineAiIconComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
