// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiChatInterfaceComponent as AiChatInterfaceComponentCustomElement,
  defineAiChatInterfaceComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-chat-interface',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiChatInterfaceComponent {
  protected elementRef = inject<ElementRef<AiChatInterfaceComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-chat-interface element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Controls whether the expand button is visible in the header */
  @Input({ transform: booleanAttribute })
  public set showExpandButton(value: AiChatInterfaceComponentCustomElement['showExpandButton']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.showExpandButton = value;
    });
  }
  public get showExpandButton(): AiChatInterfaceComponentCustomElement['showExpandButton'] {
    return this.nativeElement.showExpandButton;
  }

  /** Controls whether the minimize button is visible in the header */
  @Input({ transform: booleanAttribute })
  public set showMinimizeButton(value: AiChatInterfaceComponentCustomElement['showMinimizeButton']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.showMinimizeButton = value;
    });
  }
  public get showMinimizeButton(): AiChatInterfaceComponentCustomElement['showMinimizeButton'] {
    return this.nativeElement.showMinimizeButton;
  }

  /** Indicates the current expanded state for displaying the appropriate expand/collapse icon */
  @Input({ transform: booleanAttribute })
  public set expanded(value: AiChatInterfaceComponentCustomElement['expanded']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.expanded = value;
    });
  }
  public get expanded(): AiChatInterfaceComponentCustomElement['expanded'] {
    return this.nativeElement.expanded;
  }

  /** Controls which minimize icon to display in the header */
  @Input()
  public set minimizeIcon(value: AiChatInterfaceComponentCustomElement['minimizeIcon']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.minimizeIcon = value;
    });
  }
  public get minimizeIcon(): AiChatInterfaceComponentCustomElement['minimizeIcon'] {
    return this.nativeElement.minimizeIcon;
  }

  constructor() {
    defineAiChatInterfaceComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
