// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThemeEditorComponent } from '@tylertech/forge-extended';

import { ThemeEditorComponent } from './theme-editor.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThemeEditorComponent],
  exports: [ThemeEditorComponent]
})
export class ForgeExtendedThemeEditorModule {
  constructor() {
    defineThemeEditorComponent();
  }
}
