// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ThemeEditorComponent as ThemeEditorComponentCustomElement,
  defineThemeEditorComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-theme-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ThemeEditorComponent {
  protected elementRef = inject<ElementRef<ThemeEditorComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-theme-editor element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The theme being edited. */
  @Input()
  public set theme(value: ThemeEditorComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): ThemeEditorComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** The export format shown on the import/export view. */
  @Input()
  public set exportFormat(value: ThemeEditorComponentCustomElement['exportFormat']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.exportFormat = value;
    });
  }
  public get exportFormat(): ThemeEditorComponentCustomElement['exportFormat'] {
    return this.nativeElement.exportFormat;
  }

  /**
   * Whether the CSS and Sass exports express each derived ramp as a CSS relative
   * color of the token it came from, so changing a base updates its ramp rather
   * than leaving it frozen at export time.
   *
   * Off by default: a literal value works in every engine and every tool, and on
   * an engine without relative color support the declaration is dropped silently
   * rather than erroring.
   */
  @Input({ transform: booleanAttribute })
  public set relativeColors(value: ThemeEditorComponentCustomElement['relativeColors']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.relativeColors = value;
    });
  }
  public get relativeColors(): ThemeEditorComponentCustomElement['relativeColors'] {
    return this.nativeElement.relativeColors;
  }

  /** Returns the theme being edited. */
  public getTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['getTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['getTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.getTheme(...args));
  }

  /**
   * Replaces the theme being edited. Anything the value omits is filled in with a
   * default, so a partial theme or a bare token map is accepted.
   */
  public loadTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['loadTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['loadTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.loadTheme(...args));
  }

  /** Emits the theme in the requested format. */
  public exportTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['exportTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['exportTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.exportTheme(...args));
  }

  /**
   * Imports theme JSON, dropping unknown token names rather than emitting dead
   * custom properties.
   */
  public importTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['importTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['importTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.importTheme(...args));
  }

  /** Derives the full token set from seed colors. */
  public generatePalette(
    ...args: Parameters<ThemeEditorComponentCustomElement['generatePalette']>
  ): ReturnType<ThemeEditorComponentCustomElement['generatePalette']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.generatePalette(...args));
  }

  /** Sets one token, or clears it when the value is empty. */
  public setToken(
    ...args: Parameters<ThemeEditorComponentCustomElement['setToken']>
  ): ReturnType<ThemeEditorComponentCustomElement['setToken']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.setToken(...args));
  }

  /** Reverts one token to the Forge default for the theme's mode. */
  public resetToken(
    ...args: Parameters<ThemeEditorComponentCustomElement['resetToken']>
  ): ReturnType<ThemeEditorComponentCustomElement['resetToken']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.resetToken(...args));
  }

  /** Reverts every token in the active variant to the Forge defaults. */
  public resetAllTokens(
    ...args: Parameters<ThemeEditorComponentCustomElement['resetAllTokens']>
  ): ReturnType<ThemeEditorComponentCustomElement['resetAllTokens']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.resetAllTokens(...args));
  }

  /**
   * Reports the contrast ratio of every `on-*` token against its background,
   * worst first.
   */
  public getContrastReport(
    ...args: Parameters<ThemeEditorComponentCustomElement['getContrastReport']>
  ): ReturnType<ThemeEditorComponentCustomElement['getContrastReport']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.getContrastReport(...args));
  }

  constructor() {
    defineThemeEditorComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
