// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ThemeEditorComponent as ThemeEditorComponentCustomElement,
  defineThemeEditorComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-theme-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ThemeEditorComponent {
  protected elementRef = inject<ElementRef<ThemeEditorComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-theme-editor element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The theme being edited. */
  @Input()
  public set theme(value: ThemeEditorComponentCustomElement['theme']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.theme = value;
    });
  }
  public get theme(): ThemeEditorComponentCustomElement['theme'] {
    return this.nativeElement.theme;
  }

  /** Indicates whether the theme is currently applied to the live document. */
  @Input({ transform: booleanAttribute })
  public set preview(value: ThemeEditorComponentCustomElement['preview']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.preview = value;
    });
  }
  public get preview(): ThemeEditorComponentCustomElement['preview'] {
    return this.nativeElement.preview;
  }

  /**
   * The selectors the live preview declares its tokens on. Defaults to the
   * conventional Forge theme carriers.
   */
  @Input()
  public set previewSelectors(value: ThemeEditorComponentCustomElement['previewSelectors']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.previewSelectors = value;
    });
  }
  public get previewSelectors(): ThemeEditorComponentCustomElement['previewSelectors'] {
    return this.nativeElement.previewSelectors;
  }

  /** The export format shown on the import/export view. */
  @Input()
  public set exportFormat(value: ThemeEditorComponentCustomElement['exportFormat']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.exportFormat = value;
    });
  }
  public get exportFormat(): ThemeEditorComponentCustomElement['exportFormat'] {
    return this.nativeElement.exportFormat;
  }

  /** Returns the theme being edited. */
  public getTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['getTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['getTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.getTheme(...args));
  }

  /**
   * Replaces the theme being edited. Anything the value omits is filled in with a
   * default, so a partial theme or a bare token map is accepted.
   */
  public loadTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['loadTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['loadTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.loadTheme(...args));
  }

  /** Applies the theme to the live document. */
  public applyPreview(
    ...args: Parameters<ThemeEditorComponentCustomElement['applyPreview']>
  ): ReturnType<ThemeEditorComponentCustomElement['applyPreview']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.applyPreview(...args));
  }

  /** Removes the theme from the live document, restoring the page's own theme. */
  public removePreview(
    ...args: Parameters<ThemeEditorComponentCustomElement['removePreview']>
  ): ReturnType<ThemeEditorComponentCustomElement['removePreview']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.removePreview(...args));
  }

  /** Emits the theme in the requested format. */
  public exportTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['exportTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['exportTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.exportTheme(...args));
  }

  /**
   * Imports theme JSON, dropping unknown token names rather than emitting dead
   * custom properties.
   */
  public importTheme(
    ...args: Parameters<ThemeEditorComponentCustomElement['importTheme']>
  ): ReturnType<ThemeEditorComponentCustomElement['importTheme']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.importTheme(...args));
  }

  /** Derives the full token set from seed colors. */
  public generatePalette(
    ...args: Parameters<ThemeEditorComponentCustomElement['generatePalette']>
  ): ReturnType<ThemeEditorComponentCustomElement['generatePalette']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.generatePalette(...args));
  }

  /** Sets one token, or clears it when the value is empty. */
  public setToken(
    ...args: Parameters<ThemeEditorComponentCustomElement['setToken']>
  ): ReturnType<ThemeEditorComponentCustomElement['setToken']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.setToken(...args));
  }

  /** Reverts one token to the Forge default for the theme's mode. */
  public resetToken(
    ...args: Parameters<ThemeEditorComponentCustomElement['resetToken']>
  ): ReturnType<ThemeEditorComponentCustomElement['resetToken']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.resetToken(...args));
  }

  /** Reverts every token to the Forge defaults for the theme's mode. */
  public resetAllTokens(
    ...args: Parameters<ThemeEditorComponentCustomElement['resetAllTokens']>
  ): ReturnType<ThemeEditorComponentCustomElement['resetAllTokens']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.resetAllTokens(...args));
  }

  /**
   * Reports the contrast ratio of every `on-*` token against its background,
   * worst first.
   */
  public getContrastReport(
    ...args: Parameters<ThemeEditorComponentCustomElement['getContrastReport']>
  ): ReturnType<ThemeEditorComponentCustomElement['getContrastReport']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.getContrastReport(...args));
  }

  /** The CSS the live preview injects, whether or not the preview is applied. */
  public getPreviewCss(
    ...args: Parameters<ThemeEditorComponentCustomElement['getPreviewCss']>
  ): ReturnType<ThemeEditorComponentCustomElement['getPreviewCss']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.getPreviewCss(...args));
  }

  constructor() {
    defineThemeEditorComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
