// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiFabButtonComponent as AiFabButtonComponentCustomElement,
  defineAiFabButtonComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-fab-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiFabButtonComponent {
  protected elementRef = inject<ElementRef<AiFabButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-fab-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the button is disabled */
  @Input({ transform: booleanAttribute })
  public set disabled(value: AiFabButtonComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): AiFabButtonComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  /** Whether the button is extended */
  @Input({ transform: booleanAttribute })
  public set extended(value: AiFabButtonComponentCustomElement['extended']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.extended = value;
    });
  }
  public get extended(): AiFabButtonComponentCustomElement['extended'] {
    return this.nativeElement.extended;
  }

  constructor() {
    defineAiFabButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
