// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiFabButtonComponent } from '@tylertech/forge-extended';

import { AiFabButtonComponent } from './ai-fab-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiFabButtonComponent],
  exports: [AiFabButtonComponent]
})
export class ForgeExtendedAiFabButtonModule {
  constructor() {
    defineAiFabButtonComponent();
  }
}
