// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineCustomLinkComponent } from '@tylertech/forge-extended';

import { CustomLinkComponent } from './custom-link.component';

@NgModule({
  imports: [CommonModule],
  declarations: [CustomLinkComponent],
  exports: [CustomLinkComponent]
})
export class ForgeExtendedCustomLinkModule {
  constructor() {
    defineCustomLinkComponent();
  }
}
