// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, inject } from '@angular/core';
import {
  CustomLinkComponent as CustomLinkComponentCustomElement,
  defineCustomLinkComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-custom-link',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class CustomLinkComponent {
  protected elementRef = inject<ElementRef<CustomLinkComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-custom-link element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineCustomLinkComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
