// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiResponseMessageComponent } from '@tylertech/forge-extended';

import { AiResponseMessageComponent } from './ai-response-message.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiResponseMessageComponent],
  exports: [AiResponseMessageComponent]
})
export class ForgeExtendedAiResponseMessageModule {
  constructor() {
    defineAiResponseMessageComponent();
  }
}
