// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiResponseMessageComponent as AiResponseMessageComponentCustomElement,
  defineAiResponseMessageComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-response-message',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiResponseMessageComponent {
  protected elementRef = inject<ElementRef<AiResponseMessageComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-response-message element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  constructor() {
    defineAiResponseMessageComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
