// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiReasoningComponent as AiReasoningComponentCustomElement,
  defineAiReasoningComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-reasoning',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiReasoningComponent {
  protected elementRef = inject<ElementRef<AiReasoningComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-reasoning element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the reasoning is expanded */
  @Input({ transform: booleanAttribute })
  public set expanded(value: AiReasoningComponentCustomElement['expanded']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.expanded = value;
    });
  }
  public get expanded(): AiReasoningComponentCustomElement['expanded'] {
    return this.nativeElement.expanded;
  }

  constructor() {
    defineAiReasoningComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
