// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiGradientContainerComponent } from '@tylertech/forge-extended';

import { AiGradientContainerComponent } from './ai-gradient-container.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiGradientContainerComponent],
  exports: [AiGradientContainerComponent]
})
export class ForgeExtendedAiGradientContainerModule {
  constructor() {
    defineAiGradientContainerComponent();
  }
}
