// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiGradientContainerComponent as AiGradientContainerComponentCustomElement,
  defineAiGradientContainerComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-gradient-container',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiGradientContainerComponent {
  protected elementRef = inject<ElementRef<AiGradientContainerComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-gradient-container element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Gradient intensity variant */
  @Input()
  public set variant(value: AiGradientContainerComponentCustomElement['variant']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.variant = value;
    });
  }
  public get variant(): AiGradientContainerComponentCustomElement['variant'] {
    return this.nativeElement.variant;
  }

  constructor() {
    defineAiGradientContainerComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
