// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiSuggestionsComponent } from '@tylertech/forge-extended';

import { AiSuggestionsComponent } from './ai-suggestions.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiSuggestionsComponent],
  exports: [AiSuggestionsComponent]
})
export class ForgeExtendedAiSuggestionsModule {
  constructor() {
    defineAiSuggestionsComponent();
  }
}
