// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  StructuredCardComponent as StructuredCardComponentCustomElement,
  defineStructuredCardComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-structured-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class StructuredCardComponent {
  protected elementRef = inject<ElementRef<StructuredCardComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-structured-card element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /**
   * Controls the semantic heading level for the title content. Defaults to `2` (h2).
   * Use this to maintain proper heading hierarchy in your document structure.
   */
  @Input()
  public set headingLevel(value: StructuredCardComponentCustomElement['headingLevel']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.headingLevel = value;
    });
  }
  public get headingLevel(): StructuredCardComponentCustomElement['headingLevel'] {
    return this.nativeElement.headingLevel;
  }

  /**
   * When set to `true`, removes the default padding from the body section to accommodate
   * tables and other full-width content. This ensures tables extend edge-to-edge within the card body.
   */
  @Input({ transform: booleanAttribute })
  public set withTable(value: StructuredCardComponentCustomElement['withTable']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.withTable = value;
    });
  }
  public get withTable(): StructuredCardComponentCustomElement['withTable'] {
    return this.nativeElement.withTable;
  }

  constructor() {
    defineStructuredCardComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
