// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThoughtDetailComponent } from '@tylertech/forge-extended';

import { ThoughtDetailComponent } from './thought-detail.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThoughtDetailComponent],
  exports: [ThoughtDetailComponent]
})
export class ForgeExtendedThoughtDetailModule {
  constructor() {
    defineThoughtDetailComponent();
  }
}
