// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiReasoningHeaderComponent as AiReasoningHeaderComponentCustomElement,
  defineAiReasoningHeaderComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-reasoning-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiReasoningHeaderComponent {
  protected elementRef = inject<ElementRef<AiReasoningHeaderComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-reasoning-header element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the header is expanded */
  @Input({ transform: booleanAttribute })
  public set expanded(value: AiReasoningHeaderComponentCustomElement['expanded']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.expanded = value;
    });
  }
  public get expanded(): AiReasoningHeaderComponentCustomElement['expanded'] {
    return this.nativeElement.expanded;
  }

  /** Whether this is a reasoning header */
  @Input({ transform: booleanAttribute })
  public set reasoning(value: AiReasoningHeaderComponentCustomElement['reasoning']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.reasoning = value;
    });
  }
  public get reasoning(): AiReasoningHeaderComponentCustomElement['reasoning'] {
    return this.nativeElement.reasoning;
  }

  constructor() {
    defineAiReasoningHeaderComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
