// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiReasoningHeaderComponent } from '@tylertech/forge-extended';

import { AiReasoningHeaderComponent } from './ai-reasoning-header.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiReasoningHeaderComponent],
  exports: [AiReasoningHeaderComponent]
})
export class ForgeExtendedAiReasoningHeaderModule {
  constructor() {
    defineAiReasoningHeaderComponent();
  }
}
