// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiDropdownMenuComponent } from '@tylertech/forge-extended';

import { ForgeAiDropdownMenuComponent } from './forge-ai-dropdown-menu.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiDropdownMenuComponent],
  exports: [ForgeAiDropdownMenuComponent]
})
export class ForgeExtendedForgeAiDropdownMenuModule {
  constructor() {
    defineForgeAiDropdownMenuComponent();
  }
}
