// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineRichTextFeatureCodeComponent } from '@tylertech/forge-extended';

import { RichTextFeatureCodeComponent } from './rich-text-feature-code.component';

@NgModule({
  imports: [CommonModule],
  declarations: [RichTextFeatureCodeComponent],
  exports: [RichTextFeatureCodeComponent]
})
export class ForgeExtendedRichTextFeatureCodeModule {
  constructor() {
    defineRichTextFeatureCodeComponent();
  }
}
