// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  RichTextFeatureCodeComponent as RichTextFeatureCodeComponentCustomElement,
  defineRichTextFeatureCodeComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-rte-code',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class RichTextFeatureCodeComponent {
  protected elementRef = inject<ElementRef<RichTextFeatureCodeComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-rte-code element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The accessible label for the code button. */
  @Input()
  public set label(value: RichTextFeatureCodeComponentCustomElement['label']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.label = value;
    });
  }
  public get label(): RichTextFeatureCodeComponentCustomElement['label'] {
    return this.nativeElement.label;
  }

  public get extensions(): RichTextFeatureCodeComponentCustomElement['extensions'] {
    return this.nativeElement.extensions;
  }

  constructor() {
    defineRichTextFeatureCodeComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
