// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineForgeAiPopoverComponent } from '@tylertech/forge-extended';

import { ForgeAiPopoverComponent } from './forge-ai-popover.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ForgeAiPopoverComponent],
  exports: [ForgeAiPopoverComponent]
})
export class ForgeExtendedForgeAiPopoverModule {
  constructor() {
    defineForgeAiPopoverComponent();
  }
}
