// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ForgeAiPopoverComponent as ForgeAiPopoverComponentCustomElement,
  defineForgeAiPopoverComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-popover',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ForgeAiPopoverComponent {
  protected elementRef = inject<ElementRef<ForgeAiPopoverComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-popover element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The anchor element to position the popover relative to. */
  @Input()
  public set anchor(value: ForgeAiPopoverComponentCustomElement['anchor']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.anchor = value;
    });
  }
  public get anchor(): ForgeAiPopoverComponentCustomElement['anchor'] {
    return this.nativeElement.anchor;
  }

  /** The placement of the popover relative to the anchor. */
  @Input()
  public set placement(value: ForgeAiPopoverComponentCustomElement['placement']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.placement = value;
    });
  }
  public get placement(): ForgeAiPopoverComponentCustomElement['placement'] {
    return this.nativeElement.placement;
  }

  /** Whether the popover should flip to the opposite side when there's no space. */
  @Input({ transform: booleanAttribute })
  public set flip(value: ForgeAiPopoverComponentCustomElement['flip']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.flip = value;
    });
  }
  public get flip(): ForgeAiPopoverComponentCustomElement['flip'] {
    return this.nativeElement.flip;
  }

  /** Whether the popover should shift to stay in view. */
  @Input({ transform: booleanAttribute })
  public set shift(value: ForgeAiPopoverComponentCustomElement['shift']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.shift = value;
    });
  }
  public get shift(): ForgeAiPopoverComponentCustomElement['shift'] {
    return this.nativeElement.shift;
  }

  /** Whether the popover is open. */
  @Input({ transform: booleanAttribute })
  public set open(value: ForgeAiPopoverComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): ForgeAiPopoverComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  constructor() {
    defineForgeAiPopoverComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
