// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineThoughtImageComponent } from '@tylertech/forge-extended';

import { ThoughtImageComponent } from './thought-image.component';

@NgModule({
  imports: [CommonModule],
  declarations: [ThoughtImageComponent],
  exports: [ThoughtImageComponent]
})
export class ForgeExtendedThoughtImageModule {
  constructor() {
    defineThoughtImageComponent();
  }
}
