// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  ThoughtImageComponent as ThoughtImageComponentCustomElement,
  defineThoughtImageComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-thought-image',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ThoughtImageComponent {
  protected elementRef = inject<ElementRef<ThoughtImageComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-thought-image element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** The step number for this thought image */
  @Input()
  public set step(value: ThoughtImageComponentCustomElement['step']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.step = value;
    });
  }
  public get step(): ThoughtImageComponentCustomElement['step'] {
    return this.nativeElement.step;
  }

  constructor() {
    defineThoughtImageComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
