// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiButtonComponent as AiButtonComponentCustomElement,
  defineAiButtonComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiButtonComponent {
  protected elementRef = inject<ElementRef<AiButtonComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-button element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Whether the button is disabled */
  @Input({ transform: booleanAttribute })
  public set disabled(value: AiButtonComponentCustomElement['disabled']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.disabled = value;
    });
  }
  public get disabled(): AiButtonComponentCustomElement['disabled'] {
    return this.nativeElement.disabled;
  }

  constructor() {
    defineAiButtonComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
