// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiButtonComponent } from '@tylertech/forge-extended';

import { AiButtonComponent } from './ai-button.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiButtonComponent],
  exports: [AiButtonComponent]
})
export class ForgeExtendedAiButtonModule {
  constructor() {
    defineAiButtonComponent();
  }
}
