// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import {
  booleanAttribute,
  Component,
  ElementRef,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  NgZone,
  Input,
  inject
} from '@angular/core';
import {
  AiDialogComponent as AiDialogComponentCustomElement,
  defineAiDialogComponent
} from '@tylertech/forge-extended';

/**  */
@Component({
  selector: 'forge-ai-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class AiDialogComponent {
  protected elementRef = inject<ElementRef<AiDialogComponentCustomElement>>(ElementRef);
  protected zone = inject(NgZone);

  /** The forge-ai-dialog element. */
  public readonly nativeElement = this.elementRef.nativeElement;

  /** Indicates whether the dialog is open. */
  @Input({ transform: booleanAttribute })
  public set open(value: AiDialogComponentCustomElement['open']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.open = value;
    });
  }
  public get open(): AiDialogComponentCustomElement['open'] {
    return this.nativeElement.open;
  }

  /**
   * Controls the dialog's positioning and size behavior.
   * When true, the dialog will have an expanded width and be centered on the screen.
   * When false, the dialog will be positioned at the bottom-right corner with a fixed width.
   */
  @Input({ transform: booleanAttribute })
  public set expanded(value: AiDialogComponentCustomElement['expanded']) {
    this.zone.runOutsideAngular(() => {
      this.nativeElement.expanded = value;
    });
  }
  public get expanded(): AiDialogComponentCustomElement['expanded'] {
    return this.nativeElement.expanded;
  }

  /** Gets the current fullscreen state (readonly) */
  public get isFullscreen(): AiDialogComponentCustomElement['isFullscreen'] {
    return this.nativeElement.isFullscreen;
  }

  /** Opens the dialog. */
  public show(
    ...args: Parameters<AiDialogComponentCustomElement['show']>
  ): ReturnType<AiDialogComponentCustomElement['show']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.show(...args));
  }

  /** Closes the dialog. */
  public close(
    ...args: Parameters<AiDialogComponentCustomElement['close']>
  ): ReturnType<AiDialogComponentCustomElement['close']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.close(...args));
  }

  /** Toggles the dialog open state. */
  public toggle(
    ...args: Parameters<AiDialogComponentCustomElement['toggle']>
  ): ReturnType<AiDialogComponentCustomElement['toggle']> {
    return this.zone.runOutsideAngular(() => this.nativeElement.toggle(...args));
  }

  constructor() {
    defineAiDialogComponent();
    const changeDetectorRef = inject(ChangeDetectorRef);
    changeDetectorRef.detach();
  }
}
