// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiDialogComponent } from '@tylertech/forge-extended';

import { AiDialogComponent } from './ai-dialog.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiDialogComponent],
  exports: [AiDialogComponent]
})
export class ForgeExtendedAiDialogModule {
  constructor() {
    defineAiDialogComponent();
  }
}
