name: Build Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build and Test
    uses: tyler-technologies-oss/forge-automation-shared/.github/workflows/wf-build-and-test.yml@v2.10.3
    with:
      TESTS_ENABLED: true
      TESTS_NPM_SCRIPT: test:ci
    secrets:
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
