name: Deploy PR Preview
 
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'packages/extended/**'
 
concurrency: deploy-pr-preview-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Install pnpm
        if: github.event.action != 'closed'
        uses: pnpm/action-setup@v4
 
      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20
 
      - name: Configure pnpm
        if: github.event.action != 'closed'
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Dependencies
        if: github.event.action != 'closed'
        run: pnpm i
 
      - name: Build
        if: github.event.action != 'closed'
        run: pnpm run build:storybook:extended

      - name: Deploy Preview 🚀
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: packages/extended/storybook-static
          pages-base-path: docs/
          token: ${{ secrets.GITHUB_TOKEN }}
          umbrella-dir: docs/pr-preview
