// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineAiUserMessageComponent } from '@tylertech/forge-extended';

import { AiUserMessageComponent } from './ai-user-message.component';

@NgModule({
  imports: [CommonModule],
  declarations: [AiUserMessageComponent],
  exports: [AiUserMessageComponent]
})
export class ForgeExtendedAiUserMessageModule {
  constructor() {
    defineAiUserMessageComponent();
  }
}
